/*
 * Copyright 2026 Lambda
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.lambda.task.tasks.wrappers

import com.lambda.context.SafeContext
import com.lambda.task.Task
import com.lambda.task.Task.Ta5kBuilder
import com.lambda.task.TaskGenerator
import com.lambda.task.TaskOrNullGenerator
import com.lambda.threading.runSafe

@Ta5kBuilder
infix fun <R> Task<R>.onFail(handler: TaskGenerator<Throwable, *>) =
	OnFailTask(this, handler)

@Ta5kBuilder
infix fun <R> Task<R>.onFailOrNull(handler: TaskOrNullGenerator<Throwable, *>) =
	OnFailOrNullTask(this, handler)

@Ta5kBuilder
infix fun <R> Task<R>.withRecovery(handler: TaskGenerator<Throwable, R>) =
	RecoveryTask(this, handler)

@Ta5kBuilder
infix fun <R> Task<R>.withRecoveryOrNull(handler: SafeContext.(Throwable) -> Task<R>?) =
	OptionalRecoveryTask(this, handler)

/**
 * A task that performs a given [innerTask] with a callback task in the event the [innerTask] fails.
 *
 * Useful for when you want a certain task to trigger when another task fails.
 * If in need of a task that returns the same type to avoid further branching, see [withRecovery] or [withRecoveryOrNull].
 *
 * @see onFail
 */
class OnFailTask<R> @Ta5kBuilder internal constructor(
	private val innerTask: Task<R>,
	private val onFailTaskGenerator: TaskGenerator<Throwable, *>
) : Task<R?>() {
	override val name get() = "On fail task for ${innerTask.name}"

	override fun SafeContext.onStart() {
		innerTask
			.onSuccess { success(it) }
			.onFailure { cause ->
				onFailTaskGenerator(cause)
					.onSuccess { success(null) }
					.execute(this@OnFailTask)
			}
			.execute(this@OnFailTask)
	}

	override fun onSubTaskFailure(subTask: Task<*>, cause: Throwable) {
		if (subTask != innerTask) super.onSubTaskFailure(subTask, cause)
	}
}

/**
 * A task that performs a given [innerTask] with an optional callback task in the event the [innerTask] fails.
 *
 * Useful for when you want a certain task to trigger based on a predicate when another task fails.
 * If in need of a task that returns the same type to avoid further branching, see [withRecovery] or [withRecoveryOrNull].
 *
 * @see onFailOrNull
 */
class OnFailOrNullTask<R> @Ta5kBuilder internal constructor(
	private val innerTask: Task<R>,
	private val onFailTaskGenerator: TaskOrNullGenerator<Throwable, *>
) : Task<R?>() {
	override val name get() = "On fail task for ${innerTask.name}"

	override fun SafeContext.onStart() {
		innerTask
			.onSuccess { success(it) }
			.execute(this@OnFailOrNullTask)
	}

	override fun onSubTaskFailure(subTask: Task<*>, cause: Throwable) {
		if (subTask == innerTask) {
			runSafe {
				onFailTaskGenerator(cause)
					?.onSuccess { success(null) }
					?.execute(this@OnFailOrNullTask)
					?: super.onSubTaskFailure(subTask, cause)
			}
		} else super.onSubTaskFailure(subTask, cause)
	}
}

/**
 * A task that performs a given [innerTask] with a fallback to the task supplied by [recoveryTaskGenerator] in case of failure.
 * Both the [innerTask] and the task generated by [recoveryTaskGenerator] have the same result type.
 *
 * Useful for if you want to have a backup task to return the same result type in case the first fails.
 * This leaves the task branch clean of further branching while providing protection against individual task failure.
 *
 * @see withRecovery
 */
class RecoveryTask<R> @Ta5kBuilder internal constructor(
	private val innerTask: Task<R>,
	private val recoveryTaskGenerator: TaskGenerator<Throwable, R>,
) : Task<R>() {
	override val name get() = "Recovery task in case of failure for ${innerTask.name}"

	override fun SafeContext.onStart() {
		innerTask
			.onSuccess { success(it) }
			.onFailure { cause ->
				recoveryTaskGenerator(this, cause)
					.onSuccess { success(it) }
					.execute(this@RecoveryTask)
			}
			.execute(this@RecoveryTask)
	}

	override fun onSubTaskFailure(subTask: Task<*>, cause: Throwable) {
		if (subTask != innerTask) super.onSubTaskFailure(subTask, cause)
	}
}

/**
 * A task that performs a given [innerTask] with a fallback to the optional task supplied by [recoveryTaskGenerator] in case of failure.
 * Both the [innerTask] and the optional task generated by [recoveryTaskGenerator] have the same result type.
 *
 * Useful for if you want to have an optional backup task to return the same result type in case the first fails.
 * This leaves the task branch clean of further branching while providing protection against individual task failure, unless null is returned from [recoveryTaskGenerator].
 *
 * @see withRecovery
 */
class OptionalRecoveryTask<R> @Ta5kBuilder internal constructor(
	private val innerTask: Task<R>,
	private val recoveryTaskGenerator: TaskOrNullGenerator<Throwable, R>,
) : Task<R?>() {
	override val name get() = "Optional recovery task in case of failure for ${innerTask.name}"

	override fun SafeContext.onStart() {
		innerTask
			.onSuccess { success(it) }
			.execute(this@OptionalRecoveryTask)
	}

	override fun onSubTaskFailure(subTask: Task<*>, cause: Throwable) {
		if (subTask == innerTask) {
			runSafe {
				recoveryTaskGenerator(this, cause)
					?.onSuccess { success(it) }
					?.execute(this@OptionalRecoveryTask)
					?: super.onSubTaskFailure(subTask, cause)
			}
		} else super.onSubTaskFailure(subTask, cause)
	}
}