modLoader = "kotlinforforge"
loaderVersion = "[${kotlinForgeVersion},)"
license = "GNU General Public License v3.0"
issueTrackerURL = "https://github.com/lambda-client/lambda/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "Lambda"
authors = "${modAuthors}"
description = "${modDescription}"
logoFile = "assets/lambda/lambda.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersionMin},${forgeVersionMax}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersionMin},${minecraftVersionMax}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${kotlinForgeVersionMin},${kotlinForgeVersionMax}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "baritoe" # Baritone decided to do this, jesus fucking christ
mandatory = true
versionRange = "[${baritoneVersion},]"
ordering = "NONE"
side = "CLIENT"
