modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "GNU General Public License v3.0"

[[mods]]
modId = "lambda"
version = "${version}"
displayName = "Lambda"
authors = "${authors}"
description = '''
'''
logoFile = "assets/lambda/lambda.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.lambda]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.lambda]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.21)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.lambda]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[4,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.lambda]]
modId = "architectury"
mandatory = true
versionRange = "[7.1.86,)"
ordering = "AFTER"
side = "CLIENT"
