modLoader = "javafml"
loaderVersion = "[48,)"
license = "GNU General Public License v3.0"
issueTrackerURL = "https://github.com/lambda-client/lambda/issues"

[[mods]]
    modId = "lambda"
    version = "${mod_version}"
    displayName = "Lambda"
    authors = "${authors}"
    description = "${mod_description}"
    logoFile = "assets/lambda/lambda.png"
    displayTest = "IGNORE_ALL_VERSION"

[[dependencies.lambda]]
    modId = "forge"
    mandatory = true
    versionRange = "[49,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.lambda]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.4,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.lambda]]
    modId = "architectury"
    mandatory = true
    versionRange = "[11.0.7,)"
    ordering = "AFTER"
    side = "CLIENT"
