# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
  - '(critical|urgent)'

# Add/remove 'bug' label if issue contains the word 'bug'
bug:
  - '(bug|error|issue|problem|crash|fix|broken)'

# Add the triage label to all issues/PRs
triage:
  - '/.*/'
