# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
  - '(critical|urgent)'

# Add/remove 'bug' label if issue contains the word 'bug'
bug:
  - '(bug|error|issue|problem|crash|fix|broken)'

# Add the triage label to all issues/PRs
triage:
  - '/.*/'

fabric:
  - '\b(fabric)\b/i'

forge:
  - '\b(forge)\b/i'

neoforge:
  - '\b(neoforge)\b/i'

"1.20":
  - '1\.20(\.\d+|\.x)?'

"1.21":
  - '1\.21(\.\d+|\.x)?'
