#
# Copyright 2024 Lambda
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Lambda https://github.com/lambda-client/lambda
modId=lambda
modName=Lambda
modVersion=1.0.0
modDescription=Minecraft utility mod coded in Kotlin
modIcon=assets/lambda/lambda.png
mavenGroup=com.lambda
modAuthors=Constructor, Blade, Edouard127

# General
minecraftVersion=1.21.3
minecraftVersionMin=1.21.3
minecraftVersionMax=1.21.4
mixinExtrasVersion=0.4.1
kotlinVersion=2.1.10
kotlinxCoroutinesVersion=1.10.1
javaVersion=21
baritoneVersion=1.11.1
discordIPCVersion=7ab2e77312
ktorVersion=3.1.2
mockitoKotlin=5.4.0
mockitoInline=5.2.0
mockkVersion=1.13.17

# Fabric https://fabricmc.net/develop/
fabricLoaderVersion=0.16.9
yarnMappings=build.2
fabricApiVersion=0.109.0
kotlinFabricVersion=1.13.1+kotlin

# Forge https://files.minecraftforge.net/
forgeVersion=53.0.25
forgeVersionMin=53
forgeVersionMax=54
kotlinForgeVersion=5.6.0
kotlinForgeVersionMin=5.6.0
kotlinForgeVersionMax=6

# Kotlin https://kotlinlang.org/
kotlin.code.style=official

# Gradle https://gradle.org/
org.gradle.jvmargs=-Xmx4096M \
  -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true

org.jetbrains.dokka.experimental.gradle.pluginMode.nowarn=true
