#
# Copyright 2025 Lambda
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Lambda https://github.com/lambda-client/lambda
modId=lambda
modName=Lambda
modVersion=1.0.0
modDescription=Minecraft utility mod coded in Kotlin
modIcon=assets/lambda/lambda.png
mavenGroup=com.lambda
modAuthors=Avanatiker, Blade, beanbag44, Edouard127

# General
minecraftVersion=1.21.5
minecraftVersionMin=1.21.5
minecraftVersionMax=1.21.6
mixinExtrasVersion=0.5.0-rc.2
kotlinVersion=2.2.0
pngEncoderVersion=0.16.0
javaVersion=21
baritoneVersion=1.14.0
discordIPCVersion=7ab2e77312
classGraphVersion=4.8.179
ktorVersion=3.1.2
mockitoKotlin=5.4.0
mockitoInline=5.2.0
mockkVersion=1.13.17

# Fabric https://fabricmc.net/develop/
fabricLoaderVersion=0.16.13
yarnMappings=build.1
fabricApiVersion=0.124.0
kotlinFabricVersion=1.13.4+kotlin

# Kotlin https://kotlinlang.org/
kotlin.code.style=official

# Gradle https://gradle.org/
org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true

org.jetbrains.dokka.experimental.gradle.pluginMode.nowarn=true
