# Lambda https://github.com/lambda-client/lambda
modId=lambda
modVersion=1.0.0
modDescription=Minecraft utility mod coded in Kotlin
mavenGroup=com.lambda
modAuthors=Constructor, Blade, Edouard127

# General
minecraftVersion=1.20.4
minecraftVersionMin=1.20.3
minecraftVersionMax=1.20.4
mixinExtrasVersion=0.4.1
kotlinVersion=2.0.20
kotlinxCoroutinesVersion=1.9.0-RC
javaVersion=17
baritoneVersion=1.10.2
discordIPCVersion=7ab2e77312

# Fabric https://fabricmc.net/develop/
fabricLoaderVersion=0.15.9
yarnMappings=build.3
kotlinFabricVersion=1.12.1+kotlin

# Forge https://files.minecraftforge.net/
forgeVersion=49.1.4
forgeVersionMin=44
forgeVersionMax=49.999.0
kotlinForgeVersion=4.11.0
kotlinForgeVersionMin=4.0.0
kotlinForgeVersionMax=4.11.0

# Kotlin https://kotlinlang.org/
kotlin.code.style=official

# Gradle https://gradle.org/
org.gradle.jvmargs=-Xmx2048M \
  -XX:MaxMetaspaceSize=256m \
  -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
