/*
 * Copyright 2025 Lambda
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.lambda.util.collections

/**
 * A lazy-initialized value holder that allows the stored value to be reset and re-initialized on demand.
 *
 * This class supports lazy initialization for a value of type [T] using a provided initializer function.
 * Once the value is accessed, it is initialized and stored. The `update` function can be called to reset
 * the value, allowing it to be re-initialized using the same initializer function.
 *
 * @param T The type of the value being lazily initialized and managed.
 * @constructor Accepts an initializer function that defines how the value should be created.
 */
class UpdatableLazy<T>(private val initializer: () -> T) {
    private var _value: T? = null

    /**
     * Retrieves the lazily initialized value of type [T]. If the value has not been
     * initialized yet, it is computed using the initializer function, stored, and then returned.
     *
     * This property supports lazy initialization where the value is generated only on first access.
     * Once initialized, the value is cached for subsequent accesses, ensuring consistent behavior
     * across invocations. If the value needs to be recomputed intentionally, it can be reset externally
     * using the appropriate function in the containing class.
     *
     * @return The currently initialized or newly computed value of type [T].
     */
    val value: T get() = _value ?: initializer().also { _value = it }

    /**
     * Resets the current value to a new value generated by the initializer function.
     *
     * This function effectively re-initializes the stored value by discarding the existing value,
     * if any, and calling the initializer function to compute a new value.
     * It is useful for scenarios where the lazily computed value needs to be refreshed or updated
     * explicitly.
     */
    fun update() {
        _value = initializer()
    }
}

/**
 * Provides a lazily-initialized value that can be reset and re-initialized on demand.
 * This function utilizes an `UpdatableLazy` to manage the lazy initialization and allow updates.
 *
 * @param T The type of the value to be lazily initialized.
 * @param initializer A lambda function that defines how the value should be computed.
 * @return An `UpdatableLazy` instance capable of managing a lazily-initialized value.
 */
fun <T> updatableLazy(initializer: () -> T) = UpdatableLazy(initializer)