version: 1

labels:
  - label: 'bug'
    title: '(\[|)bug(?=(:|]))'

  - label: 'feature'
    title: '(\[|)(feature|feat)(?=(:|]))'

  - label: 'forge'
    title: '(\[|)forge(?=(:|]))'

  - label: 'neoforge'
    title: '(\[|)neoforge(?=(:|]))'

  - label: 'fabric'
    title: '(\[|)fabric(?=(:|]))'

  - label: '1.20'
    title: '(\[|)1\.20(\.\d+|\.x)?(?=(:|]|))'

  - label: 'wip'
    type: "pull_request"
    mergeable: false

  - label: 'triage'
    title: '.*'
    mergeable: false
