modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "GNU General Public License v3.0"

[[mods]]
modId = "lambda"
version = "${version}"
displayName = "Lambda"
authors = "${authors}"
description = "${description}"
logoFile = "assets/lambda/lambda.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.lambda]]
modId = "neoforge"
mandatory = true
type = "required"
versionRange = "[20.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.lambda]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[1.20.2,1.21)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.lambda]]
modId = "kotlinforforge"
mandatory = true
type = "required"
versionRange = "[4,)"
ordering = "AFTER"
side = "CLIENT"
