modLoader = "kotlinforforge"
loaderVersion = "[${kotlinForgeVersion},)"
license = "GNU General Public License v3.0"
issueTrackerURL = "https://github.com/lambda-client/lambda/issues"
#updateJSONURL = "https://raw.githubusercontent.com/lambda-client/lambda/main/update.json"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "Lambda"
authors = "${modAuthors}"
description = "${modDescription}"
logoFile = "assets/lambda/lambda.png"
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "lambda.mixins.common.json"

[[dependencies.${modId}]]
modId = "neoforge"
mandatory = true
type = "required"
versionRange = "[${neoVersionMin},${neoVersionMax}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[${minecraftVersionMin},${minecraftVersionMax}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "kotlinforforge"
mandatory = true
type = "required"
versionRange = "[${kotlinForgeVersionMin},${kotlinForgeVersionMax}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "baritoe" # Baritone decided to do this, jesus fucking christ
mandatory = true
versionRange = "[${baritoneVersion},]"
ordering = "NONE"
side = "CLIENT"
