package com.lambda.client.module.modules.player

import com.lambda.client.event.events.PacketEvent
import com.lambda.client.module.Category
import com.lambda.client.module.Module
import com.lambda.event.listener.listener
import net.minecraft.network.login.client.*
import net.minecraft.network.login.server.*
import net.minecraft.network.play.client.*
import net.minecraft.network.play.server.*
import net.minecraft.network.play.server.SPacketDisconnect
import net.minecraft.network.status.client.*
import net.minecraft.network.status.server.*

object PacketCancel : Module(
    name = "PacketCancel",
    description = "Cancels specific packets used for various actions",
    category = Category.PLAYER
) {
    enum class PageEnum {
        Client, Server
    }

    val page by setting("Page", PageEnum.Client)

    private val CPacketAnimationSetting by setting("CPacketAnimation", false, { page == PageEnum.Client})
    private val CPacketUseEntitySetting by setting("CPacketUseEntity", false, { page == PageEnum.Client})
    private val CPacketChatMessageSetting by setting("CPacketChatMessage", false, { page == PageEnum.Client})
    private val CPacketClickWindowSetting by setting("CPacketClickWindow", false, { page == PageEnum.Client})
    private val CPacketClientSettingsSetting by setting("CPacketClient", false, { page == PageEnum.Client})
    private val CPacketClientStatusSetting by setting("CPacketClientStatus", false, { page == PageEnum.Client})
    private val CPacketCloseWindowSetting by setting("CPacketCloseWindow", false, { page == PageEnum.Client})
    private val CPacketConfirmTeleportSetting by setting("CPacketConfirmTeleport", false, { page == PageEnum.Client})
    private val CPacketConfirmTransactionSetting by setting("CPacketConfirmTransaction", false, { page == PageEnum.Client})
    private val CPacketCreativeInventoryActionSetting by setting("CPacketCreativeInventoryAction", false, { page == PageEnum.Client})
    private val CPacketCustomPayloadSetting by setting("CPacketCustomPayload", false, { page == PageEnum.Client})
    private val CPacketEnchantItemSetting by setting("CPacketEnchantItem", false, { page == PageEnum.Client})
    private val CPacketEntityActionSetting by setting("CPacketEntityAction", false, { page == PageEnum.Client})
    private val CPacketPlayerSetting by setting("CPacketPlayer", false, { page == PageEnum.Client})
    private val CPacketHeldItemChangeSetting by setting("CPacketHeldItemChange", false, { page == PageEnum.Client})
    private val CPacketInputSetting by setting("CPacketInput", false, { page == PageEnum.Client})
    private val CPacketPlaceRecipeSetting by setting("CPacketPlaceRecipe", false, { page == PageEnum.Client})
    private val CPacketPlayerAbilitiesSetting by setting("CPacketPlayerAbilities", false, { page == PageEnum.Client})
    private val CPacketPlayerTryUseItemSetting by setting("CPacketPlayerTryUseItem", false, { page == PageEnum.Client})
    private val CPacketPlayerTryUseItemOnBlockSetting by setting("CPacketPlayerTryUseItemOnBlock", false, { page == PageEnum.Client})
    private val CPacketServerQuerySetting by setting("CPacketServerQuery", false, { page == PageEnum.Client})
    private val CPacketLoginStartSetting by setting("CPacketLoginStart", false, { page == PageEnum.Client})
    private val CPacketPingSetting by setting("CPacketPing", false, { page == PageEnum.Client})
    private val CPacketEncryptionResponseSetting by setting("CPacketEncryptionResponse", false, { page == PageEnum.Client})
    private val CPacketVehicleMoveSetting by setting("CPacketVehicleMove", false, { page == PageEnum.Client})
    private val CPacketUpdateSignSetting by setting("CPacketUpdateSign", false, { page == PageEnum.Client})
    private val CPacketTabCompleteSetting by setting("CPacketTabComplete", false, { page == PageEnum.Client})
    private val CPacketSteerBoatSetting by setting("CPacketSteerBoat", false, { page == PageEnum.Client})
    private val CPacketSpectateSetting by setting("CPacketSpectate", false, { page == PageEnum.Client})
    private val CPacketSeenAdvancementsSetting by setting("CPacketSeenAdvancements", false, { page == PageEnum.Client})
    private val CPacketResourcePackStatusSetting by setting("CPacketResourcePackStatus", false, { page == PageEnum.Client})
    private val CPacketRecipeInfoSetting by setting("CPacketRecipeInfo", false, { page == PageEnum.Client})
    private val CPacketPlayerDiggingSetting by setting("CPacketPlayerDigging", false, { page == PageEnum.Client})
    private val CPacketKeepAliveSetting by setting("CPacketKeepAlive", false, { page == PageEnum.Client})

    private val SPacketEntityS17PacketEntityLookMoveSetting by setting("SPacketEntity.S17PacketEntityLookMove", false, { page == PageEnum.Server})
    private val SPacketEntityS16PacketEntityLookSetting by setting("SPacketEntity.S16PacketEntityLook", false, { page == PageEnum.Server})
    private val SPacketEntityS15PacketEntityRelMoveSetting by setting("SPacketEntity.S15PacketEntityRelMove", false, { page == PageEnum.Server})
    private val SPacketServerInfoSetting by setting("SPacketServerInfo", false, { page == PageEnum.Server})
    private val SPacketLoginSuccessSetting by setting("SPacketLoginSuccess", false, { page == PageEnum.Server})
    private val SPacketWorldBorderSetting by setting("SPacketWorldBorder", false, { page == PageEnum.Server})
    private val SPacketWindowPropertySetting by setting("SPacketWindowProperty", false, { page == PageEnum.Server})
    private val SPacketWindowItemsSetting by setting("SPacketWindowItems", false, { page == PageEnum.Server})
    private val SPacketPongSetting by setting("SPacketPong", false, { page == PageEnum.Server})
    private val SPacketEncryptionRequestSetting by setting("SPacketEncryptionRequest", false, { page == PageEnum.Server})
    private val SPacketEnableCompressionSetting by setting("SPacketEnableCompression", false, { page == PageEnum.Server})
    private val SPacketDisconnectSetting by setting("SPacketDisconnect", false, { page == PageEnum.Server})
    private val SPacketUseBedSetting by setting("SPacketUseBed", false, { page == PageEnum.Server})
    private val SPacketUpdateTileEntitySetting by setting("SPacketUpdateTileEntity", false, { page == PageEnum.Server})
    private val SPacketUpdateScoreSetting by setting("SPacketUpdateScore", false, { page == PageEnum.Server})
    private val SPacketUpdateHealthSetting by setting("SPacketUpdateHealth", false, { page == PageEnum.Server})
    private val SPacketUpdateBossInfoSetting by setting("SPacketUpdateBossInfo", false, { page == PageEnum.Server})
    private val SPacketUnloadChunkSetting by setting("SPacketUnloadChunk", false, { page == PageEnum.Server})
    private val SPacketTitleSetting by setting("SPacketTitle", false, { page == PageEnum.Server})
    private val SPacketTimeUpdateSetting by setting("SPacketTimeUpdate", false, { page == PageEnum.Server})
    private val SPacketTeamsSetting by setting("SPacketTeams", false, { page == PageEnum.Server})
    private val SPacketTabCompleteSetting by setting("SPacketTabComplete", false, { page == PageEnum.Server})
    private val SPacketStatisticsSetting by setting("SPacketStatistics", false, { page == PageEnum.Server})
    private val SPacketSpawnPositionSetting by setting("SPacketSpawnPosition", false, { page == PageEnum.Server})
    private val SPacketSpawnPaintingSetting by setting("SPacketSpawnPainting", false, { page == PageEnum.Server})
    private val SPacketSpawnObjectSetting by setting("SPacketSpawnObject", false, { page == PageEnum.Server})
    private val SPacketSpawnPlayerSetting by setting("SPacketSpawnPlayer", false, { page == PageEnum.Server})
    private val SPacketSpawnMobSetting by setting("SPacketSpawnMob", false, { page == PageEnum.Server})
    private val SPacketSpawnGlobalEntitySetting by setting("SPacketSpawnGlobalEntity", false, { page == PageEnum.Server})
    private val SPacketSpawnExperienceOrbSetting by setting("SPacketSpawnExperienceOrb", false, { page == PageEnum.Server})
    private val SPacketSoundEffectSetting by setting("SPacketSoundEffect", false, { page == PageEnum.Server})
    private val SPacketSignEditorOpenSetting by setting("SPacketSignEditorOpen", false, { page == PageEnum.Server})
    private val SPacketSetSlotSetting by setting("SPacketSetSlot", false, { page == PageEnum.Server})
    private val SPacketSetExperienceSetting by setting("SPacketSetExperience", false, { page == PageEnum.Server})
    private val SPacketServerDifficultySetting by setting("SPacketServerDifficulty", false, { page == PageEnum.Server})
    private val SPacketSelectAdvancementsTabSetting by setting("SPacketSelectAdvancementsTab", false, { page == PageEnum.Server})
    private val SPacketScoreboardObjectiveSetting by setting("SPacketScoreboardObjective", false, { page == PageEnum.Server})
    private val SPacketRespawnSetting by setting("SPacketRespawn", false, { page == PageEnum.Server})
    private val SPacketResourcePackSendSetting by setting("SPacketResourcePackSend", false, { page == PageEnum.Server})
    private val SPacketRemoveEntityEffectSetting by setting("SPacketRemoveEntityEffect", false, { page == PageEnum.Server})
    private val SPacketRecipeBookSetting by setting("SPacketRecipeBook", false, { page == PageEnum.Server})
    private val SPacketPlayerListItemSetting by setting("SPacketPlayerListItem", false, { page == PageEnum.Server})
    private val SPacketPlayerListHeaderFooterSetting by setting("SPacketPlayerListHeaderFooter", false, { page == PageEnum.Server})
    private val SPacketPlayerAbilitiesSetting by setting("SPacketPlayerAbilities", false, { page == PageEnum.Server})
    private val SPacketPlaceGhostRecipeSetting by setting("SPacketPlaceGhostRecipe", false, { page == PageEnum.Server})
    private val SPacketParticlesSetting by setting("SPacketParticles", false, { page == PageEnum.Server})
    private val SPacketOpenWindowSetting by setting("SPacketOpenWindow", false, { page == PageEnum.Server})
    private val SPacketMultiBlockChangeSetting by setting("SPacketMultiBlockChange", false, { page == PageEnum.Server})
    private val SPacketMapsSetting by setting("SPacketMaps", false, { page == PageEnum.Server})
    private val SPacketKeepAliveSetting by setting("SPacketKeepAlive", false, { page == PageEnum.Server})
    private val SPacketJoinGameSetting by setting("SPacketJoinGame", false, { page == PageEnum.Server})
    private val SPacketHeldItemChangeSetting by setting("SPacketHeldItemChange", false, { page == PageEnum.Server})
    private val SPacketExplosionSetting by setting("SPacketExplosion", false, { page == PageEnum.Server})
    private val SPacketEntityVelocitySetting by setting("SPacketEntityVelocity", false, { page == PageEnum.Server})
    private val SPacketEntityTeleportSetting by setting("SPacketEntityTeleport", false, { page == PageEnum.Server})
    private val SPacketEntityStatusSetting by setting("SPacketEntityStatus", false, { page == PageEnum.Server})
    private val SPacketEntityPropertiesSetting by setting("SPacketEntityProperties", false, { page == PageEnum.Server})
    private val SPacketEntityMetadataSetting by setting("SPacketEntityMetadata", false, { page == PageEnum.Server})
    private val SPacketEntityHeadLookSetting by setting("SPacketEntityHeadLook", false, { page == PageEnum.Server})
    private val SPacketEntityEquipmentSetting by setting("SPacketEntityEquipment", false, { page == PageEnum.Server})
    private val SPacketEntityEffectSetting by setting("SPacketEntityEffect", false, { page == PageEnum.Server})
    private val SPacketEntityAttachSetting by setting("SPacketEntityAttach", false, { page == PageEnum.Server})
    private val SPacketEffectSetting by setting("SPacketEffect", false, { page == PageEnum.Server})
    private val SPacketDisplayObjectiveSetting by setting("SPacketDisplayObjective", false, { page == PageEnum.Server})
    private val SPacketDestroyEntitiesSetting by setting("SPacketDestroyEntities", false, { page == PageEnum.Server})
    private val SPacketCustomSoundSetting by setting("SPacketCustomSound", false, { page == PageEnum.Server})
    private val SPacketCustomPayloadSetting by setting("SPacketCustomPayload", false, { page == PageEnum.Server})
    private val SPacketCooldownSetting by setting("SPacketCooldown", false, { page == PageEnum.Server})
    private val SPacketConfirmTransactionSetting by setting("SPacketConfirmTransaction", false, { page == PageEnum.Server})
    private val SPacketCombatEventSetting by setting("SPacketCombatEvent", false, { page == PageEnum.Server})
    private val SPacketCollectItemSetting by setting("SPacketCollectItem", false, { page == PageEnum.Server})
    private val SPacketCloseWindowSetting by setting("SPacketCloseWindow", false, { page == PageEnum.Server})
    private val SPacketChunkDataSetting by setting("SPacketChunkData", false, { page == PageEnum.Server})
    private val SPacketChatSetting by setting("SPacketChat", false, { page == PageEnum.Server})
    private val SPacketChangeGameStateSetting by setting("SPacketChangeGameState", false, { page == PageEnum.Server})
    private val SPacketCameraSetting by setting("SPacketCamera", false, { page == PageEnum.Server})
    private val SPacketBlockChangeSetting by setting("SPacketBlockChange", false, { page == PageEnum.Server})
    private val SPacketBlockBreakAnimSetting by setting("SPacketBlockBreakAnim", false, { page == PageEnum.Server})
    private val SPacketBlockActionSetting by setting("SPacketBlockAction", false, { page == PageEnum.Server})
    private val SPacketAnimationSetting by setting("SPacketAnimation", false, { page == PageEnum.Server})
    private val SPacketAdvancementInfoSetting by setting("SPacketAdvancementInfo", false, { page == PageEnum.Server})

    init {
        listener<PacketEvent.Send> {
            when(it.packet) {
                is CPacketAnimation -> if (CPacketAnimationSetting) it.cancel()
                is CPacketUseEntity  -> if (CPacketUseEntitySetting) it.cancel()
                is CPacketChatMessage -> if (CPacketChatMessageSetting) it.cancel()
                is CPacketClickWindow -> if (CPacketClickWindowSetting) it.cancel()
                is CPacketClientSettings -> if (CPacketClientSettingsSetting) it.cancel()
                is CPacketClientStatus -> if (CPacketClientStatusSetting) it.cancel()
                is CPacketCloseWindow -> if (CPacketCloseWindowSetting) it.cancel()
                is CPacketConfirmTeleport -> if (CPacketConfirmTeleportSetting) it.cancel()
                is CPacketConfirmTransaction -> if (CPacketConfirmTransactionSetting) it.cancel()
                is CPacketCreativeInventoryAction -> if (CPacketCreativeInventoryActionSetting) it.cancel()
                is CPacketCustomPayload -> if (CPacketCustomPayloadSetting) it.cancel()
                is CPacketEnchantItem -> if (CPacketEnchantItemSetting) it.cancel()
                is CPacketEntityAction -> if (CPacketEntityActionSetting) it.cancel()
                is CPacketPlayer -> if (CPacketPlayerSetting) it.cancel()
                is CPacketHeldItemChange -> if (CPacketHeldItemChangeSetting) it.cancel()
                is CPacketInput -> if (CPacketInputSetting) it.cancel()
                is CPacketPlaceRecipe -> if (CPacketPlaceRecipeSetting) it.cancel()
                is CPacketPlayerAbilities -> if (CPacketPlayerAbilitiesSetting) it.cancel()
                is CPacketPlayerTryUseItem -> if (CPacketPlayerTryUseItemSetting) it.cancel()
                is CPacketPlayerTryUseItemOnBlock -> if (CPacketPlayerTryUseItemOnBlockSetting) it.cancel()
                is CPacketServerQuery -> if (CPacketServerQuerySetting) it.cancel()
                is CPacketLoginStart -> if (CPacketLoginStartSetting) it.cancel()
                is CPacketPing -> if (CPacketPingSetting) it.cancel()
                is CPacketEncryptionResponse -> if (CPacketEncryptionResponseSetting) it.cancel()
                is CPacketVehicleMove -> if (CPacketVehicleMoveSetting) it.cancel()
                is CPacketUpdateSign -> if (CPacketUpdateSignSetting) it.cancel()
                is CPacketTabComplete -> if (CPacketTabCompleteSetting) it.cancel()
                is CPacketSteerBoat -> if (CPacketSteerBoatSetting) it.cancel()
                is CPacketSpectate -> if (CPacketSpectateSetting) it.cancel()
                is CPacketSeenAdvancements -> if (CPacketSeenAdvancementsSetting) it.cancel()
                is CPacketResourcePackStatus -> if (CPacketResourcePackStatusSetting) it.cancel()
                is CPacketRecipeInfo -> if (CPacketRecipeInfoSetting) it.cancel()
                is CPacketPlayerDigging -> if (CPacketPlayerDiggingSetting) it.cancel()
                is CPacketKeepAlive -> if (CPacketKeepAliveSetting) it.cancel()
            }
        }
        listener<PacketEvent.Receive> {
            when (it.packet) {
                is SPacketEntity.S17PacketEntityLookMove -> if(SPacketEntityS17PacketEntityLookMoveSetting) it.cancel()
                is SPacketEntity.S16PacketEntityLook -> if(SPacketEntityS16PacketEntityLookSetting) it.cancel()
                is SPacketEntity.S15PacketEntityRelMove -> if(SPacketEntityS15PacketEntityRelMoveSetting) it.cancel()
                is SPacketServerInfo -> if(SPacketServerInfoSetting) it.cancel()
                is SPacketLoginSuccess -> if(SPacketLoginSuccessSetting) it.cancel()
                is SPacketWorldBorder -> if(SPacketWorldBorderSetting) it.cancel()
                is SPacketWindowProperty -> if(SPacketWindowPropertySetting) it.cancel()
                is SPacketWindowItems -> if(SPacketWindowItemsSetting) it.cancel()
                is SPacketPong -> if(SPacketPongSetting) it.cancel()
                is SPacketEncryptionRequest -> if(SPacketEncryptionRequestSetting) it.cancel()
                is SPacketEnableCompression -> if(SPacketEnableCompressionSetting) it.cancel()
                is SPacketDisconnect -> if(SPacketDisconnectSetting) it.cancel()
                is SPacketUseBed -> if(SPacketUseBedSetting) it.cancel()
                is SPacketUpdateTileEntity -> if(SPacketUpdateTileEntitySetting) it.cancel()
                is SPacketUpdateScore -> if(SPacketUpdateScoreSetting) it.cancel()
                is SPacketUpdateHealth -> if(SPacketUpdateHealthSetting) it.cancel()
                is SPacketUpdateBossInfo -> if(SPacketUpdateBossInfoSetting) it.cancel()
                is SPacketUnloadChunk -> if(SPacketUnloadChunkSetting) it.cancel()
                is SPacketTitle -> if(SPacketTitleSetting) it.cancel()
                is SPacketTimeUpdate -> if(SPacketTimeUpdateSetting) it.cancel()
                is SPacketTeams -> if(SPacketTeamsSetting) it.cancel()
                is SPacketTabComplete -> if(SPacketTabCompleteSetting) it.cancel()
                is SPacketStatistics -> if(SPacketStatisticsSetting) it.cancel()
                is SPacketSpawnPosition -> if(SPacketSpawnPositionSetting) it.cancel()
                is SPacketSpawnPainting -> if(SPacketSpawnPaintingSetting) it.cancel()
                is SPacketSpawnObject -> if(SPacketSpawnObjectSetting) it.cancel()
                is SPacketSpawnPlayer -> if(SPacketSpawnPlayerSetting) it.cancel()
                is SPacketSpawnMob -> if(SPacketSpawnMobSetting) it.cancel()
                is SPacketSpawnGlobalEntity -> if(SPacketSpawnGlobalEntitySetting) it.cancel()
                is SPacketSpawnExperienceOrb -> if(SPacketSpawnExperienceOrbSetting) it.cancel()
                is SPacketSoundEffect -> if(SPacketSoundEffectSetting) it.cancel()
                is SPacketSignEditorOpen -> if(SPacketSignEditorOpenSetting) it.cancel()
                is SPacketSetSlot -> if(SPacketSetSlotSetting) it.cancel()
                is SPacketSetExperience -> if(SPacketSetExperienceSetting) it.cancel()
                is SPacketServerDifficulty -> if(SPacketServerDifficultySetting) it.cancel()
                is SPacketSelectAdvancementsTab -> if(SPacketSelectAdvancementsTabSetting) it.cancel()
                is SPacketScoreboardObjective -> if(SPacketScoreboardObjectiveSetting) it.cancel()
                is SPacketRespawn -> if(SPacketRespawnSetting) it.cancel()
                is SPacketResourcePackSend -> if(SPacketResourcePackSendSetting) it.cancel()
                is SPacketRemoveEntityEffect -> if(SPacketRemoveEntityEffectSetting) it.cancel()
                is SPacketRecipeBook -> if(SPacketRecipeBookSetting) it.cancel()
                is SPacketPlayerListItem -> if(SPacketPlayerListItemSetting) it.cancel()
                is SPacketPlayerListHeaderFooter -> if(SPacketPlayerListHeaderFooterSetting) it.cancel()
                is SPacketPlayerAbilities -> if(SPacketPlayerAbilitiesSetting) it.cancel()
                is SPacketPlaceGhostRecipe -> if(SPacketPlaceGhostRecipeSetting) it.cancel()
                is SPacketParticles -> if(SPacketParticlesSetting) it.cancel()
                is SPacketOpenWindow -> if(SPacketOpenWindowSetting) it.cancel()
                is SPacketMultiBlockChange -> if(SPacketMultiBlockChangeSetting) it.cancel()
                is SPacketMaps -> if(SPacketMapsSetting) it.cancel()
                is SPacketKeepAlive -> if(SPacketKeepAliveSetting) it.cancel()
                is SPacketJoinGame -> if(SPacketJoinGameSetting) it.cancel()
                is SPacketHeldItemChange -> if(SPacketHeldItemChangeSetting) it.cancel()
                is SPacketExplosion -> if(SPacketExplosionSetting) it.cancel()
                is SPacketEntityVelocity -> if(SPacketEntityVelocitySetting) it.cancel()
                is SPacketEntityTeleport -> if(SPacketEntityTeleportSetting) it.cancel()
                is SPacketEntityStatus -> if(SPacketEntityStatusSetting) it.cancel()
                is SPacketEntityProperties -> if(SPacketEntityPropertiesSetting) it.cancel()
                is SPacketEntityMetadata -> if(SPacketEntityMetadataSetting) it.cancel()
                is SPacketEntityHeadLook -> if(SPacketEntityHeadLookSetting) it.cancel()
                is SPacketEntityEquipment -> if(SPacketEntityEquipmentSetting) it.cancel()
                is SPacketEntityEffect -> if(SPacketEntityEffectSetting) it.cancel()
                is SPacketEntityAttach -> if(SPacketEntityAttachSetting) it.cancel()
                is SPacketEffect -> if(SPacketEffectSetting) it.cancel()
                is SPacketDisplayObjective -> if(SPacketDisplayObjectiveSetting) it.cancel()
                is SPacketDestroyEntities -> if(SPacketDestroyEntitiesSetting) it.cancel()
                is SPacketCustomSound -> if(SPacketCustomSoundSetting) it.cancel()
                is SPacketCustomPayload -> if(SPacketCustomPayloadSetting) it.cancel()
                is SPacketCooldown -> if(SPacketCooldownSetting) it.cancel()
                is SPacketConfirmTransaction -> if(SPacketConfirmTransactionSetting) it.cancel()
                is SPacketCombatEvent -> if(SPacketCombatEventSetting) it.cancel()
                is SPacketCollectItem -> if(SPacketCollectItemSetting) it.cancel()
                is SPacketCloseWindow -> if(SPacketCloseWindowSetting) it.cancel()
                is SPacketChunkData -> if(SPacketChunkDataSetting) it.cancel()
                is SPacketChat -> if(SPacketChatSetting) it.cancel()
                is SPacketChangeGameState -> if(SPacketChangeGameStateSetting) it.cancel()
                is SPacketCamera -> if(SPacketCameraSetting) it.cancel()
                is SPacketBlockChange -> if(SPacketBlockChangeSetting) it.cancel()
                is SPacketBlockBreakAnim -> if(SPacketBlockBreakAnimSetting) it.cancel()
                is SPacketBlockAction -> if(SPacketBlockActionSetting) it.cancel()
                is SPacketAnimation -> if(SPacketAnimationSetting) it.cancel()
                is SPacketAdvancementInfo -> if(SPacketAdvancementInfoSetting) it.cancel()
            }
        }
    }
}