name: Build Lambda

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    name: Build Lambda
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Get Short Commit Hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set-Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          architecture: x64
          cache: 'gradle'

      - name: Read Gradle Properties
        uses: BrycensRanch/read-properties-action@v1.0.4
        id: all
        with:
          file: gradle.properties
          all: true

      - name: Build Lambda
        run: ./gradlew build --no-daemon

      - name: Rename Files with Commit Hash
        run: |
          mv ./build/libs/lambda-${{ steps.all.outputs.modVersion }}+${{ steps.all.outputs.minecraftVersion }}.jar ./build/libs/lambda-${{ steps.all.outputs.modVersion }}+${{ steps.all.outputs.minecraftVersion }}-${{ env.COMMIT_HASH }}.jar

      - name: Upload Lambda
        uses: ryand56/r2-upload-action@latest
        id: upload
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY }}
          r2-secret-access-key: ${{ secrets.R2_ACCESS_SECRET }}
          r2-bucket: ${{ secrets.R2_BUCKET_NAME }}
          source-dir: |
            ./build/libs/lambda-${{ steps.all.outputs.modVersion }}+${{ steps.all.outputs.minecraftVersion }}.jar
          destination-dir: ${{ env.DATE }}-${{ env.COMMIT_HASH }}

      - name: Generate Summary
        if: ${{ steps.upload.outputs.result == 'success' }}
        run: |
          cat << EOF >> $GITHUB_STEP_SUMMARY
          ### [Lambda ${{ steps.all.outputs.modVersion }} ${{ steps.all.outputs.minecraftVersion }} (${{ env.COMMIT_HASH }})](https://r2-bucket.edouard127.christmas/${{ env.DATE }}-${{ env.COMMIT_HASH }}/lambda-${{ steps.all.outputs.modVersion }}+${{ steps.all.outputs.minecraftVersion }}-${{ env.COMMIT_HASH }}.jar)
          EOF

      - name: Failover Upload
        if: ${{ steps.upload.outputs.result == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: lambda-nightly
          path: |
            /build/libs/lambda-*-${{ steps.all.outputs.modVersion }}+${{ steps.all.outputs.minecraftVersion }}-${{ env.COMMIT_HASH }}.jar
        
        
