name: Build Lambda

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check-runner:
    runs-on: ubuntu-latest
    
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}
    
    steps:
      - name: Set runner
        id: set-runner
        run: |
          runners=$(curl -v -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runners" --http1.1)
          if [ $? -ne 0 ]; then
            echo "Error: Failed to fetch runners from GitHub API" >&2
            exit 1
          fi

          runners_count=$(echo "$runners" | jq '.runners | length')
          if [ "$runners_count" -eq 0 ]; then
            echo "No runners available or failed to retrieve runners." >&2
            echo "runner-label=ubuntu-latest" >> $GITHUB_OUTPUT
            exit 0
          fi
    
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" and .busy == false and .labels[] .name == "self-hosted")')
          if [ $? -ne 0 ]; then
            echo "Error: Failed to parse JSON response" >&2
            exit 1
          fi
    
          if [ -n "$available" ]; then
            echo "runner-label=lambda-linux-runner" >> $GITHUB_OUTPUT
          else
            echo "runner-label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi
  build:
    needs: check-runner
    runs-on: ${{ needs.check-runner.outputs.runner-label }}
    
    name: Build Lambda
    permissions:
      contents: write
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set current date as env variable
        run: echo "DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Get Short Commit Hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set-Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          architecture: x64
          cache: 'gradle'
          cache-dependency-path: |
            build.gradle.kts

      - name: Read Gradle Properties
        uses: BrycensRanch/read-properties-action@v1.0.4
        id: all
        with:
          file: gradle.properties
          all: true

      - name: Build Lambda
        run: ./gradlew --build-cache build

      - name: Upload Lambda
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY }}
          r2-secret-access-key: ${{ secrets.R2_ACCESS_SECRET }}
          r2-bucket: ${{ secrets.R2_BUCKET_NAME }}
          source-dir: |
            fabric/build/libs/lambda-fabric-${{ steps.all.outputs.modVersion }}+${{ steps.all.outputs.minecraftVersion }}
            forge/build/libs/lambda-forge-${{ steps.all.outputs.modVersion }}+${{ steps.all.outputs.minecraftVersion }}
            common/build/libs/lambda-api-${{ steps.all.outputs.modVersion }}+${{ steps.all.outputs.minecraftVersion }}
          destination-dir: ${{ env.DATE }}-${{ env.COMMIT_HASH }}
