name: Release Lambda

on:
  push:
    tags:
      - '*'

jobs:
  build_and_release:
    name: Build and Release Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          architecture: x64
          cache: 'gradle'
          cache-dependency-path: |
            build.gradle.kts

      - name: Read Gradle Properties
        uses: BrycensRanch/read-properties-action@v1.0.4
        id: all
        with:
          file: gradle.properties
          all: true

      - name: Build Lambda
        run: ./gradlew --build-cache build

      - name: Upload Lambda Fabric
        uses: actions/upload-artifact@v4.3.6
        with:
          name: lambda-fabric
          path: fabric/build/libs/

      - name: Upload Lambda Forge
        uses: actions/upload-artifact@v4.3.6
        with:
          name: lambda-forge
          path: forge/build/libs/

      - name: Upload Lambda NeoForge
        uses: actions/upload-artifact@v4.3.6
        with:
          name: lambda-neoforge
          path: neoforge/build/libs/

      - name: Upload Lambda API
        uses: actions/upload-artifact@v4.3.6
        with:
          name: lambda-api
          path: common/build/libs/

      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4.1.1
        with:
          commitMode: true
          configurationJson: |
            {
              "pr_template": "- #{{TITLE}} [#{{AUTHOR}}](#{{URL}})"
            }

      - name: Create release
        uses: softprops/action-gh-release@v2.0.8
        with:
          name: Lambda ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: false
          files: |
            fabric/build/libs/lambda-fabric-*.jar
            forge/build/libs/lambda-forge-*.jar
            neoforge/build/libs/lambda-neoforge-*.jar
            common/build/libs/lambda-*.jar