name: Run Tests

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    name: Build Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set-Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          architecture: x64
          cache: 'gradle'

      - name: Build Lambda
        run: ./gradlew common:test
